/* Generated by tooling/png2epd.py - do not edit */
#ifndef EPD_IMAGE_H
#define EPD_IMAGE_H

#include "epd.h"

/* Black/white plane and red plane, EPD_PLANE_BYTES each.
   0 = ink, 1 = white; pass to epd_upload(0x10/0x13, ...). */
extern const unsigned char epd_image_bw[EPD_PLANE_BYTES];
extern const unsigned char epd_image_red[EPD_PLANE_BYTES];

#endif /* EPD_IMAGE_H */
